{
 "title": "Host Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "topcount", "label": "Maxitems", "query": "25" }
  ]
 },
 "panels": [
  {
   "title": "Inbound vs Outbound",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    { "target": "//agg/DIR_INTOHOME/0/", "type": "timeserie" },
    {
     "target": "//agg/DIR_OUTOFHOME/0/{\"scale\":\"-1\"}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Active Flows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "//Meta Session Group/{99A78737-4B41-4387-8F31-8077DB917336}/0",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Latest Top Internal Hosts - Total",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "//Internal Host/latest toppers($topcount)/0",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top External Hosts - Total",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "target": "//External Host/latest toppers($topcount)/0",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top Internal Hosts - In Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "target": "//Internal Host/latest toppers($topcount)/1",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top External Hosts - In  Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "target": "//External Host/latest toppers($topcount)/1",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top Internal Hosts -Out Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "target": "//Internal Host/latest toppers($topcount)/2",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top External Hosts - Out  Traffic",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "target": "//External Host/latest toppers($topcount)/2",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top Internal Hosts  - Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "target": "//Internal Host/latest toppers($topcount)/4",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Top External Hosts -Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "target": "//External Host/latest toppers($topcount)/4",
     "type": "table"
    }
   ]
  }
 ]
}